# Generated by Django 4.1.3 on 2022-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0002_alter_task_options_remove_tag_tasks_task_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="todo_list_app.tag"),
        ),
    ]
