# Generated by Django 4.1.3 on 2022-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0003_remove_task_tasks_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
